### PR TITLE
Sending raw JSON/XML data as request body

### PR DESCRIPTION
**Pull request by dlid**
Sometimes you need to send a JSON or XML string as the request body content (not using GET).

I added a "body" string option where you can provide the raw body string you wish to send.

````
marmottajax({
    url: "/post.asm",
    method: "post",
    body: '{ "Answer" : 42 }',
    headers : {
        "Content-Type" : "application/json"
    }
})
````

I also noticed that when you specify the "Content-Type" header option it will be appended to the default content type header, so I added a control so the default Content-Type header is not added if the body option is set. Maybe this one could be done in a more general way - maybe never add the default Content-Type header if one is available in the headers option?

See this as a suggestion of how it could be done, but I'm sure you who have been working on this project for a while will have some input.

Cheers!

/David

### CODE REVIEW

**Comment by houd1ni** [comment]
It's OK, but will you add some tests in  `samples` folder?
And what's the profit of sending raw json? It's not clear for me yet.
If it has, your work will carried to ver.2 :)

It will be done  as XML/JSON switcher in ver.2 with many other advances, inl\cluding `Content-type` magic, that is already done in very draft version of 2. Will add it to GitHub soon.

**Comment by dlid** [comment]
Hi, I included one test in the samples folder where a raw json string is posted (index.html was updated and body.php was added).

So to the reason for this - I work currently with .NET a lot and in .NET it's a fairly common thing to receive a raw json object, and then to have it automatically deserialized to a typed .NET object when you receive it.

In the example below, I receive a "NewUser" object as a raw JSON string in the body, and .NET will deserialize it to an object of type "NewUser".

`````
[System.Web.Http.HttpPost]
public IHttpActionResult CreateUser([FromBody]NewUser user)
{
    if (FormUtility.ValidateEmail(user.Email)) {
    }
}
````

This was currently the main reason for it, but I also know of SOAP webservices that receive XML as the raw body.

Looking forward to version 2 :)

**Comment by houd1ni** [comment]
@dlid Hmm, understood. But it certainly need to be easy-serializible to be isomorphic. I.e. body: {a: 'foo', b: 'bar'} as parameters instead of '{"a": "foo", "b": "bar"}'. And a similar way with XML.  This, I guess, should be serialized inside of the Library by JSON.stringify. Is this way easier?) If yes, I'll add it in the next version and, probably, if something would be too heavy, place it as dynamic modules, that is one of new features.

**Comment by dlid** [comment]
@houd1ni Yeah, true - since you work with the objects and not the JSON string in JavaScript they should easily be serializable by the library.

But I'm thinking it would still be good to be able to send a "custom whatever string" as well, so it does not have to be valid XML or JSON. Just for more flexibility, and perhaps even to avoid the library from growing heavy...

In jQuery you can do it by setting the option `processData` to false, but then you must set the string body to the already serialized JSON string (like with my `body `option). Using JSON.stringify is when you set the parameter is not a huge deal, and it would make it very flexible - and probably less heavy than trying to detect what to use to serialize the parameter value.
````````
{
 "processData" : false,
 "data" : JSON.stringify(object)
}
````````
Perhaps something similar to that. If you set `processData` parameter to false and then `parameters` to anything other than a string, you could JSON.stringify it inside the library.

````
{
 "processData" : false,
 "parameters" : myObject
}
````

**Comment by houd1ni** [comment]
@dlid Sure. Only for irregular data. (!~['json', 'xml', ...].indexOf(input_type or so)) :)

**Pull request merged**
